{"name": "Ввод плохого ключа должен выводить ошибку", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/step_license.py\", line 34, in step_impl\n    context.browser.get(appAddress(context) + path)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 320, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 306, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py\", line 464, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py\", line 526, in _request\n    resp = opener.open(request, timeout=self._timeout)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 526, in open\n    response = self._open(req, data)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 544, in _open\n    '_open', req)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n    result = func(*args)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 1346, in http_open\n    return self.do_open(http.client.HTTPConnection, req)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 1321, in do_open\n    r = h.getresponse()\n  File \"/usr/local/lib/python3.6/http/client.py\", line 1331, in getresponse\n    response.begin()\n  File \"/usr/local/lib/python3.6/http/client.py\", line 297, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/local/lib/python3.6/http/client.py\", line 258, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/local/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n"}, "steps": [{"name": "Допустим открыли мы страницу платформы /dashboard/login", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/step_license.py\", line 34, in step_impl\n    context.browser.get(appAddress(context) + path)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 320, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 306, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py\", line 464, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py\", line 526, in _request\n    resp = opener.open(request, timeout=self._timeout)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 526, in open\n    response = self._open(req, data)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 544, in _open\n    '_open', req)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n    result = func(*args)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 1346, in http_open\n    return self.do_open(http.client.HTTPConnection, req)\n  File \"/usr/local/lib/python3.6/urllib/request.py\", line 1321, in do_open\n    r = h.getresponse()\n  File \"/usr/local/lib/python3.6/http/client.py\", line 1331, in getresponse\n    response.begin()\n  File \"/usr/local/lib/python3.6/http/client.py\", line 297, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/local/lib/python3.6/http/client.py\", line 258, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/local/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\n"}, "start": 1510127975558, "stop": 1510128063715}, {"name": "И это оказалась страница ввода лицензии", "status": "skipped", "start": 1510128063716, "stop": 1510128063716}, {"name": "Если мы вводим invalid_key в качестве ключа для пользователя test_user@directual.com", "status": "skipped", "start": 1510128063716, "stop": 1510128063716}, {"name": "То отображается ошибка", "status": "skipped", "start": 1510128063716, "stop": 1510128063716}], "start": 1510127975548, "stop": 1510128063718, "uuid": "205c90b4-fcee-499c-b80f-57b778e8299d", "historyId": "1d2869dfbbc20e42cefcb0d0a1eeb0e8", "labels": [{"name": "severity", "value": "minor"}, {"name": "feature", "value": "Лицензионные ключи и вход в систему"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}